var $=function(s){return document.querySelector(s)},cl=function(v){return Math.max(0,Math.min(1,v))};
var T=[["HTML","#c084fc"],["Laravel","#67e8f9"],["SEO","#f0abfc"],["PHP","#34d399"],["Python","#fbbf24"],["Marketing","#c084fc"],["JavaScript","#67e8f9"],["Leadership","#34d399"]];
var orbit=$("#orbit"),tiles=T.map(function(t){var d=document.createElement("div");d.className="tile";d.textContent=t[0];d.style.background=t[1];orbit.appendChild(d);return d});
var qp=$("#qp");qp.innerHTML=qp.textContent.split(" ").map(function(w){return'<span class="w">'+w+"</span>"}).join(" ");var ws=qp.querySelectorAll(".w");
var pin=$("#pin"),stages=[].slice.call(pin.querySelectorAll(".stage")),qe=$("#quote"),cyc=$("#cyc"),nav=$("#nav");
function frame(){var vh=innerHeight,r=pin.getBoundingClientRect(),p=cl(-r.top/(r.height-vh));
stages.forEach(function(s){var a=s.dataset.r.split(",").map(Number),o;if(p<a[0]||p>a[3])o=0;else if(p<a[1])o=(p-a[0])/(a[1]-a[0]);else if(p>a[2])o=1-(p-a[2])/(a[3]-a[2]);else o=1;o=cl(o);s.style.opacity=o;s.style.transform="translateY("+(1-o)*26+"px)";s.style.pointerEvents=o>.6?"auto":"none"});
var q=qe.getBoundingClientRect(),qg=cl(-q.top/(q.height-vh)*1.3);ws.forEach(function(w,k){w.classList.toggle("on",k/ws.length<qg+.05)});
var c=cyc.getBoundingClientRect(),cp=(vh-c.top)/(vh+c.height);
tiles.forEach(function(t,k){var a=k/tiles.length*6.283+cp*6.9;t.style.transform="translate("+Math.cos(a)*c.width*.42+"px,"+Math.sin(a)*c.height*.36+"px) rotate("+Math.sin(a)*8+"deg)"});
nav.classList.toggle("s",scrollY>60);var m=document.documentElement.scrollHeight-vh;$("#bar").style.transform="scaleX("+(m>0?scrollY/m:0)+")"}
addEventListener("scroll",frame,{passive:true});addEventListener("resize",frame);frame();
var W=["scale","inspire","win","rank","last"],cw=$("#cw"),wi=0;cw.innerHTML=W.map(function(w){return"<span>"+w+"</span>"}).join("");var cs=cw.children;cs[0].className="on";
setInterval(function(){var o=cs[wi];o.className="out";wi=(wi+1)%cs.length;var n=cs[wi];n.style.transition="none";n.className="";void n.offsetWidth;n.style.transition="";n.className="on";setTimeout(function(){o.className=""},750)},2300);
var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}})},{threshold:.12});
document.querySelectorAll(".rv,.lc").forEach(function(e){io.observe(e)});
var nio=new IntersectionObserver(function(es){es.forEach(function(e){if(!e.isIntersecting)return;nio.unobserve(e.target);var n=+e.target.dataset.count,t0=performance.now();(function f(t){var k=cl((t-t0)/1500);e.target.textContent=Math.round(n*(1-Math.pow(1-k,3)));if(k<1)requestAnimationFrame(f)})(t0)})},{threshold:.6});document.querySelectorAll("[data-count]").forEach(function(e){nio.observe(e)});
var IM=['20.jpg','16.png','9.png','12.png','13.jpg','24.jpg','14.png','22.jpg','8.jpg','21.jpg','29.png','27.png','25.jpg','28.jpg','1.jpeg','18.png','15.jpg','26.jpg','3.png','5.png','23.jpg','6.jpg','7.png','30.png','2.jpg','4.jpg','11.jpg','17.jpg','19.jpg','31.jpg','32.jpeg','33.jpeg','34.jpeg','35.jpeg','36.jpeg','37.jpeg','38.jpeg'],csr=$("#cs"),lb=$("#lb");
IM.forEach(function(s,i){var d=document.createElement("div");d.className="ct";d.setAttribute("role","button");d.tabIndex=0;var im=document.createElement("img");im.src=s;im.loading="lazy";im.alt="Certificate "+(i+1)+" earned by Ruzana Khan";im.onerror=function(){im.remove();d.textContent="Certificate "+(i+1)};d.onclick=function(){$("#li").src=s;lb.classList.add("on")};d.onkeydown=function(e){if(e.key==="Enter")d.onclick()};d.appendChild(im);csr.appendChild(d)});
$("#pv").onclick=function(){csr.scrollBy({left:-380,behavior:"smooth"})};$("#nx").onclick=function(){csr.scrollBy({left:380,behavior:"smooth"})};
$("#lc").onclick=function(){lb.classList.remove("on")};lb.onclick=function(e){if(e.target===lb)lb.classList.remove("on")};addEventListener("keydown",function(e){if(e.key==="Escape")lb.classList.remove("on")});
